### ISSUE TITLE
ニュースを追加したい

### ISSUE THREAD

**Issue by KenshoFujisaki** [Localia/company_homepage#11]
# ToDo
- [ ] ニュース種別がどのくらいあるのか決める（プレスリリース、セミナー、休業アナウンス等）
- [ ] ニュースの表現形式を決める（トップページだけに簡単に記載するのか、同記載をリンク化してリンクをクリックすると個別ページに飛ばすのか）
- [ ] HTML/CSS/JSを作成する
- [ ] 1ニュースを追加してみて、動作確認する
